include: package:pedantic/analysis_options.yaml

linter:
  rules:
    # Error rules
    - avoid_print
    - avoid_relative_lib_imports
    - avoid_type_to_string
    - avoid_web_libraries_in_flutter
    - empty_statements
    - no_duplicate_case_values
    - unnecessary_statements
    # Style Rules
    - always_put_control_body_on_new_line
    - avoid_catching_errors
    - avoid_classes_with_only_static_members
    - avoid_escaping_inner_quotes
    - avoid_unnecessary_containers
    - empty_catches
    - empty_constructor_bodies
    - missing_whitespace_between_adjacent_strings
    - overridden_fields
    - prefer_contains
    - prefer_foreach
    - unnecessary_final
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_this
    - slash_for_doc_comments
