name: Test Apple
on: [push]

jobs: 
  test-apple:
    runs-on: macos-latest

    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        with: 
          persist-credentials: false

      - name: Setup Java & Flutter
        uses: actions/setup-java@v1
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
      
      - name: Install dependencies
        uses: flutter pub get

      - name: Verify formatting
        run: flutter format --set-exit-if-changed .

      - name: Analyze project
        run: flutter analyze .

      # - name: Run tests
      #   run: flutter test

      - name: Build Apple
        run: flutter build apk && flutter build ios --release --no-codesign